[package]
name = "rust_webserserver"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.7"
html-escape = "0.2"
